FROM quay.io/podman/stable:v5.2

RUN dnf install -y systemd git python3 python3-pip nodejs && dnf clean all

RUN pip3 install --upgrade copier==9.3.1 hatch==1.13.0 

RUN mkdir -p /home/podman/.config/systemd/user /home/podman/.config/containers/systemd

RUN mkdir -p /var/lib/systemd/linger && \
    touch /var/lib/systemd/linger/podman && \
    chown -R 1000:1000 /home/podman

RUN sed -i.bak '/netns="host"/d' /etc/containers/containers.conf
RUN sed -i.bak '/runtime="crun"/runtime="runc"/d' /etc/containers/containers.conf

ENTRYPOINT /sbin/init
