name: Build and Push Image
on: [push]

jobs:
  build-base:
    name: Build and push base image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: pinp-molecule
          tags: latest ${{ github.sha }}
          containerfiles: |
            ./CONTAINERFILE

      - name: Push To quay.io
        id: push-to-quay
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: quay.io/speakintelnet
          username: speakintelnet+git_push
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Print image url
        run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"
  build-runc:
    name: Build and push runc image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: pinp-molecule
          tags: runc-latest ${{ github.sha }}
          containerfiles: |
            ./CONTAINERFILE-RUNC

      - name: Push To quay.io
        id: push-to-quay
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: quay.io/speakintelnet
          username: speakintelnet+git_push
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Print image url
        run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"
